// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DynamicLineChart: typeof import('./src/components/DynamicLineChart.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NSlider: typeof import('naive-ui')['NSlider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
