// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DynamicLineChart: typeof import('./src/components/DynamicLineChart.vue')['default']
    DynamicMonitorChart: typeof import('./src/components/DynamicMonitorChart.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LineChart: typeof import('./src/components/LineChart.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MonitorChart: typeof import('./src/components/MonitorChart.vue')['default']
    NavMenu: typeof import('./src/components/NavMenu.vue')['default']
    NCollapse: typeof import('naive-ui')['NCollapse']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NSelect: typeof import('naive-ui')['NSelect']
    NSlider: typeof import('naive-ui')['NSlider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
